[package]
name = "darknet-sys"
version = "0.1.0"
authors = ["alianse77 <alianse77@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.51.1"
copy_dir = "0.1.2"
cc = "1.0.50"

